"""empty message

Revision ID: 0d4d7104b09b
Revises: 3c1c54d01898
Create Date: 2023-07-22 00:58:32.855838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4d7104b09b'
down_revision = '3c1c54d01898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('post_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_code', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
