"""empty message

Revision ID: 3c1c54d01898
Revises: 117b42b663f1
Create Date: 2023-07-22 00:53:32.818825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1c54d01898'
down_revision = '117b42b663f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_date', sa.DateTime(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('venue_needed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('page_link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('music_genres', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('talent_needed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('talent_needed')
        batch_op.drop_column('description')
        batch_op.drop_column('music_genres')
        batch_op.drop_column('page_link')
        batch_op.drop_column('post_code')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('venue_needed')
        batch_op.drop_column('page_link')

    op.drop_table('Show')
    # ### end Alembic commands ###
