"""empty message

Revision ID: 548d65fd68ba
Revises: 7ef3d304b76f
Create Date: 2023-07-22 01:37:34.835363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '548d65fd68ba'
down_revision = '7ef3d304b76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        music_genres = postgresql.ENUM('ALTERNATIVE', 'BLUES', 'CLASSICAL', 'COUNTRY', 'ELECTRONIC', 'FOLK', 'FUNK', 'HIP_HOP', 'HEAVY_METAL', 'INSTRUMENTAL', 'JAZZ', 'THEATRE', 'POP', 'PUNK', 'R_AND_B', 'REGGAE', 'ROCK_N_ROLL', 'SOUL', 'OTHER', name='musictypes', create_type=False)
        music_genres.create(batch_op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column('music_genres', sa.ARRAY(music_genres), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('music_genres')

    # ### end Alembic commands ###
