"""empty message

Revision ID: 7ef3d304b76f
Revises: 0d4d7104b09b
Create Date: 2023-07-22 01:37:11.866033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef3d304b76f'
down_revision = '0d4d7104b09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('page_link')

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=120), nullable=True))
        batch_op.drop_column('page_link')
        batch_op.drop_column('music_genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music_genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('page_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###
